### PR TITLE
Issue/map colored markers date

### PR DESCRIPTION
**Pull request by olen-d**
Different colored markers for the different issues. Also added the date updated to the description when a pin is clicked on.

### CODE REVIEW

**Review by heincm — CHANGES_REQUESTED** [review]
Can we remove the console.log on line 57? I read today that logging anything to the console can slow down our mobile app.

Other than that, looks good. I like the colored markers and that the date shows up. This is great. Good work, Salvador 😉

**Review by kpatel1209 — COMMENTED** [review]
Salvador, the colors are beautiful.  Awesome job!  I'll review and approve after Chris' comments are addressed.

**Comment by olen-d** [comment]
I’ll remove that console.log this evening - nice catch, I thought I had gotten all of them.

**Comment by olen-d** [comment]
console.log removed - we should be good to go. Thanks everyone!

**Review by heincm — APPROVED** [review]
Looks good. Salvador FTW! 🦄 🌈 🔥

**Review by kpatel1209 — APPROVED** [review]
Salvador, you're an allstar!  This works perfectly!

**Pull request merged**
