### PR TITLE
Report issues cleanup

### PR DESCRIPTION
**Pull request by heincm**
Changes made:

- Added new issues and removed issues
- Added new icons to go along with new issues
- Removed icons for issues no longer used
- Added descriptions for each issue
- Added longPress event to show issue descriptions
- Added appropriate api route to post data to database
- Removed unneeded lines of code

### CODE REVIEW

**Review by kpatel1209 — CHANGES_REQUESTED** [review]
The new icons look good and the longPress event works well on an android.

A couple of grammatical changes:
- change "you" to "your" on the more information sentence and add a period at the end
- add periods at the end of each explanation for Close Calls

**Review by kpatel1209 — DISMISSED** [review]
wifey = happy :)

**Review by kpatel1209 — APPROVED** [review]
Changes look good.

**Review by olen-d — APPROVED** [review]
Nice work- thanks for taking this on.

**Pull request merged**
