### PR TITLE
Stay logged in and attach userid to reported issue

### PR DESCRIPTION
**Pull request by olen-d**

### CODE REVIEW

**Review by kpatel1209 — CHANGES_REQUESTED** [review]
- If the user initially logs in as a Guest, then they will not be able to log in as a user because the app now bypasses the Login screen and goes straight to the View Issues screen when reloading the app.  Is it possible to add a "Sign Out" feature so they have the option to log in as a user or even create a account?

- I also logged an issue under Guest, but the UserId posted as null in the db.

- The "/" in front of https for the fetch on the View Issues file breaks the app so I think it needs to be removed.

**Comment by olen-d** [comment]
- I looked into the logout and wasn't able to implement due to confusion. My thinking is we would add a logout option to the drawer navigation, add some code to clear AsyncStorage and then send them back to the login screen. I'm not clear on if it's possible to run the code to clear AsyncStorage from the drawer, or if we need to send the user to another-  screen and run the code there.

- The userId will post as null until the backend is merged and deployed.

- Fixed the /, that was a typo. Nice catch.

**Review by heincm — APPROVED** [review]
I really like not having to log in each time the app is opened. Awesome.

**Review by kpatel1209 — APPROVED** [review]
not having to log in each time is great, i will work on implementing a logout option.  nice work!

**Pull request merged**
